config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  resources :learning_resources

  get "pages/:page" => "pages#show"
end

app/models/learning_resource.rb
class LearningResource < ActiveRecord::Base
  enum age_category: [ :kid, :teenager, :adult ]
  enum delivery_method: [ :online, :face2face ]
  enum location: [ :online_l, :Wellington ]
  enum event_category: [ :course, :club, :individual, :online_e, :workshop ]
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/learning_resources_controller.rb
class LearningResourcesController < ApplicationController

  def index
    @learning_resources = LearningResource.all
  end

  def new
    @learning_resource = LearningResource.new
  end

  def create
    @learning_resource = LearningResource.new(learning_resource_params)
    @learning_resource.save

    redirect_to learning_resource_path(@learning_resource)
  end

  def show
    @learning_resource = LearningResource.find(params[:id])

  end

  def learning_resource_params
    params.require(:learning_resource).permit(
      :name,
      :description,
      :age_category,
      :delivery_method,
      :location,
      :event_category,
      :cost,
      :image_link,
      :website_link
    )
  end

end


#
# {"utf8"=>"✓",
#  "authenticity_token"=>"pzox1ItquiKD3lruBg7nTvI1hg9jm2iGau9X2sn1E5ISGk5ZMHWRm6HfkxWtQSx0qGjgcpw9ftLev3cg+V61gg==",
#  "learning_resource"=>{"name"=>"aksjdfklasjdf",
#  "description"=>"kasdflasdf",
#  "age_category"=>"kid",
#  "delivery_method"=>"online",
#  "location"=>"online_l",
#  "event_category"=>"course",
#  "cost"=>"aksdjfklajs",
#  "website_link"=>"askdjfaslk",
#  "image_link"=>"asjdflkasd"},
#  "commit"=>"Create Learning resource"}

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/learning_resources_helper.rb
module LearningResourcesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn to Code NZ" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn to Code NZ" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' unless current_page?(root_path) %>
    </header>
      <%= render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>

app/views/learning_resources/index.html.erb
<!-- Index page for learning resources, will who unfiltered list of all learning resources -->

<!-- Need to fix what is happening at top of pages -->
<br>
<br>
<br>

<h1>All Learning Resources</h1>

<div class="row text-center">
  <% @learning_resources.each do | learning_resource | %>
    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <%= link_to (image_tag (learning_resource.image_link)), learning_resource_path(learning_resource), :class => "learning_resource-home imageBoxShadow" %>
      </div>

      <div class="caption">
        <h3> <%= learning_resource.name %> </h3>
        <p>Age: <%= learning_resource.age_category %> </p>
        <p>Method: <%= learning_resource.delivery_method %> </p>
        <p>Where: <%= learning_resource.location %> </p>
        <p>Type: <%= learning_resource.event_category %> </p>
        <p>Cost: <%= learning_resource.cost %> </p>
        <p><%= learning_resource.description %> </p>
        <%= link_to "website", "http://#{learning_resource.website_link}", :class => "btn btn-primary", :target => "_blank"%>
        <%= link_to "View", learning_resource_path(learning_resource),  :class => "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/learning_resources/new.html.erb
<!-- New page - first step of adding a new learning resource -->

<!-- Need to fix what is happening at top of pages -->
<br>
<br>
<br>

<h1>Create a Learning Resource</h1>


<%= form_for(@learning_resource) do |f| %>
  <ul>
    <% @learning_resource.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :age_category %><br>
    <%= f.select :age_category, LearningResource.age_categories.keys, {} %>
  </p>
  <p>
    <%= f.label :delivery_method %><br />
    <%= f.select :delivery_method, LearningResource.delivery_methods.keys, {} %>
  </p>
  <p>
    <%= f.label :location %><br />
    <%= f.select :location, LearningResource.locations.keys, {} %>
  </p>
  <p>
    <%= f.label :event_category %><br />
    <%= f.select :event_category, LearningResource.event_categories.keys, {} %>
  </p>
  <p>
    <%= f.label :cost %><br />
    <%= f.text_area :cost %>
  </p>
  <p>
    <%= f.label :website_link %><br />
    <%= f.text_area :website_link %>
  </p>
  <p>
    <%= f.label :image_link %><br />
    <%= f.text_area :image_link %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/learning_resources/show.html.erb
<!-- New page - first step of adding a new learning resource -->

<!-- Need to fix what is happening at top of pages -->
<br>
<br>
<br>


<h1><%= @learning_resource.name %></h1>
<p><%= @learning_resource.description %></p>
<p><%= image_tag @learning_resource.image_link %></p>
<p>Age: <%= @learning_resource.age_category %> </p>
<p>Method: <%= @learning_resource.delivery_method %> </p>
<p>Where: <%= @learning_resource.location %> </p>
<p>Type: <%= @learning_resource.event_category %> </p>
<p>Cost: <%= @learning_resource.cost %> </p>
<p><%= @learning_resource.description %> </p>
<p><%= link_to "website", "http://#{@learning_resource.website_link}", :target => "_blank"%> </p>


<%= link_to "<< Back to Learning Resources", learning_resources_path %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<div class="container">
  <br>
  <br>
  <br>
  <h3>About the Website</h3>
  <p>
    This site is a proof of concept idea. Coming from a background of teaching digital technology, I have felt that there has never been a good site for people to go to to find out about where they can learn to code.
  </p>
  <p>
    This site is an attempt to do something about it. It is a work in progress.
  </p>



  <p>
    This web application was created with
    <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
    from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
  </p>


</div>

<!-- Footer -->
<footer>
  <div class="container">
    <hr class="intro-divider">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <%= link_to "Home ", root_path, class: "footer-menu-divider" %>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#about">About</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <!-- <li>
            <a href="#contact">Contact</a>
          </li> -->
          <li>
            <a href="https://twitter.com/SchuKnight" target="_blank">Twitter</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="https://schuknight.wordpress.com/" target="_blank">Blog</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="https://github.com/libbyschuknight/learn-to-code-nz" target="_blank">Github</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand topnav" href="#">Learn 2 Code NZ/A</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/pages/about">About</a>
        </li>

        <li>
          <a href="#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<!-- Header -->
<a name="about"></a>
<div class="intro-header">
  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">
          <h1>Learn 2 Code / Ako 2 Waehere</h1>
          <h2>akoranga </h2>
          <h2>uhingaro / kōrero huna / tohu muna </h2>
          <h3>Where can I Learn 2 Code in New Zealand / Aotearoa</h3>
          <hr class="intro-divider">
          <ul class="list-inline intro-social-buttons flex-container">
            <li class="flex-item btn btn-default">
              I'm a young kid
            </li>
            <li class="flex-item btn btn-default">
              I'm a teenager
            </li>
            <li class="flex-item btn btn-default">
              I'm an adult
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>  <!-- /.container -->
</div>  <!-- /.intro-header -->

<!-- Page Content -->

<!-- Footer -->
<footer>
  <div class="container">
    <hr class="intro-divider">

    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <a href="#">Home</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#about">About</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <!-- <li>
            <a href="#contact">Contact</a>
          </li> -->
          <li>
            <a href="https://twitter.com/SchuKnight" target="_blank">Twitter</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="https://schuknight.wordpress.com/" target="_blank">Blog</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="https://github.com/libbyschuknight/learn-to-code-nz" target="_blank">Github</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>